# standard jekyll configuration

permalink: /:year/:month/:day/:title/
pygments:  true
markdown: rdiscount
exclude: ['readme.md', 'Rakefile', 'config.rb', '.gitignore', '.sass-cache', 'Gemfile', 'Gemfile.lock']

title: The Praxis Network

# Program content

## Praxis Program
praxis-program:
  mission: 'To equip the next generation of knowledge workers for faculty positions and alternative academic careers "at a moment when new questions can be asked and new systems built."'
  people: 'An annual cohort of six students from a variety of disciplines, directed by <a href="http://nowviskie.org">Bethany Nowviskie</a>. Fellows receive mentoring and instruction from Scholars’ Lab faculty and staff.'
  research: 'The first cohort prototyped <a href="http://prism.scholarslab.org/">Prism</a>, a digital humanities tool for collective reading, or "crowdsourcing interpretation." The second cohort is rethinking, revising, and extending the Prism framework.'
  support: 'Supported through its two-year pilot period by the Mellon Foundation. Next year’s funding comes from the University of Virginia Library, which houses the program and also supports the <a href="http://scholarslab.org">Scholars’ Lab</a>.'
  directions: 'The curriculum will be adjusted continually, based on participant interest and the potential of various projects to make meaningful interventions in contemporary digital humanities discourse—which is construed as including both DH theory and praxis.'
  structure: 'This one-year funded fellowship features weekly meetings, a single, collaborative project common to all fellows and staff, and iterative, public sharing of outcomes and teaching materials.'
  implementation: 'Keys for success include significant staff time for high-quality mentorship, adequate space for collaborative work, and flexibility to accommodate the various backgrounds and skill levels of the fellows.'

## CHI Initiative
chi-initiative:
  mission: 'To prepare graduate students to creatively apply emerging technologies to historical and cultural heritage materials, influence the current state of digital history & cultural heritage informatics, and become thought leaders for the future of the field.'
  people: 'Directed by Ethan Watrall, the fellowship progrom comprises a small cohort of graduate students from disciplines related to cultural heritage, while the fieldschool is open to graduate and undergraduate students and selected non-students.'
  research: 'Fellows’ wide-ranging projects include a <a href="http://futbol.matrix.msu.edu/">digital dissertation prototype</a> and a <a href="http://talus.matrix.msu.edu/">web app for forensic anthropologists and bioarchaeologists</a>.'
# Ethan plans to put up a page showcasing fellows and their projects very soon, which we can then point to from this page.
  support: 'The program is supported by internal funding, not grants, and comes from the MSU Graduate School, the College of Social Science, and the Department of Anthropology.'
  directions: 'Watrall aspires to continually refine the program based on each year’s successes and challenges to create a sustainable and rigorous program in which fellows complete robust projects in their areas of interest.'
  structure: 'The two key programs are fellowships, year-long funded opportunities to develop digital projects and skills; and fieldschools, 5-6 week theme-based immersive sessions for instruction and collaborative project development.'
  implementation: 'Because the program is credit-bearing, it is important to consider how those credits will be useful across different departments, and how to evaluate process-oriented work. Also, certain disciplinary methods and paradigms may be unfamiliar for students.'

## Hope Mellon
hope-mellon-scholars:
  mission: 'To encourage deep collaboration among humanities students and faculty; to strengthen engagement with digital humanities on the institutional level; and to showcase student achievement.'
  people: 'A highly selective undergraduate program directed by William Pannapacker, Mellon Scholars also involves faculty representatives from all departments in the Arts and Humanities division of the college.'
  research: 'Students have <a href="http://celebration.hope.edu/abstracts/listing_titles.asp?CELDEP_RID=1226">completed a wide range of research projects and presented them to the community.'
  support: 'The program is currently funded by a grant from the Mellon Foundation, supplemented by modest internal funding to support release time for faculty.'
  directions: 'Two signs of success would be deeper engagement among the faculty, and an increasing number of applications to make the program more selective.'
  structure: 'This three-year project includes a two-semester interdisciplinary seminar; a year-long, Oxford-style tutorial; summer study; and a capstone project for public presentation.'
  implementation: 'Implementation text.'

## CUNY GCDI
cuny-gcdi:
  mission: 'To develop and highlight a broad range of digital projects and resources at the CUNY Graduate Center, and to foster institutional change across the CUNY campuses by heightening the public presence of digital efforts.'
  people: 'Directed by Matt Gold under the purview of the Provost’s Office, the first cohort of digital fellows are doctoral students from a variety of backgrounds.'
  research: 'While still in the early stages of development, the first cohort of fellows are leading a <a href="http://digitalfellows.commons.gc.cuny.edu/projects/">variety of innovative projects</a> to advance the digital initiatives of the Graduate Center.'
  support: 'Financial support for the program is completely internal to the Provost’s Office, which signals a strong institutional commitment.'
  directions: 'This new program is experimental, so many successes and challenges are anticipated. One hope is to retain some students in subsequent years to build up a base of knowledge and expertise.'
  structure: 'The program provides a one-year renewable fellowship with an expectation of 15 hours of work per week; fellows meet weekly to gain skills and discuss projects.'
  implementation: 'Implementation text.'

## UCL DH
ucldh:
  mission: 'To equip students to work on problems that are interesting scholarship—both from a humanities perspective and from a computer science/engineering perspective.'
  people: 'This master’s-level program is highly interdisciplinary; students enter with a range of backgrounds and participate in modules across the faculties. The program is directed by Claire Warwick and Melissa Terras.'
  research: 'Because the modules are brief and varied, students build a body of knowledge rather than focusing on a single project. As a whole, the Centre produces <a href="http://www.ucl.ac.uk/dh/projects">an impressive range of intellectually rich work products.</a>'
  support: 'While initial funding for the program has been provided by the university, the program expects to become self-sustaining through student fees and research grants.'
  directions: 'Program leaders hope to expand collaboration to include more faculty and students, while sustaining high enrollment despite recent changes in fee structures at UK universities.'
  structure: 'Depending on background and goals, students work towards an MA or MSc degree during three terms of study. The first two terms include various modules of coursework, while the third focuses on a thesis project and job placement.'
  implementation: 'Implementation text.'

